---
- hosts: all
  become: true
  gather_facts: yes
  handlers:
    - name: docker status
      service: name=docker state=started
    - name: kubelet status
      service: name=kubelet state=started
    - name: containerd status
      service: name=containerd state=started
  tasks:
  - name: Check war files in release
    local_action: stat path="/vagrant/.ssh/id_rsa.pub"
    register: key_file


  - name: Set authorized key taken from file
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '/vagrant/.ssh/id_rsa.pub') }}"
    when: key_file.stat.exists == True

      
  - name: Reset existing cluster components if any
    command: kubeadm reset -f

  - name: Remove default IP route for service network
    command: "ip route flush 10.96.0.0/16"

  - name: Recursively remove directory
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /root/.kube
      - /etc/cni/net.d 
      - /etc/kubernetes 
      - /var/lib/etcd 
      - /var/lib/kubelet 
      - /var/run/kubernetes 
      - /var/lib/cni 
      - /opt/cni

  - name: Iptables flush filter
    ansible.builtin.iptables:
      flush: yes
 
  - name: Configure default IP route for service network
    command: "ip route add 10.96.0.0/16 dev enp0s8 src {{ ansible_enp0s8.ipv4.address }}"

  - name: Restart kubelet and docker daemon
    service:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
    with_items:
      - docker
      - kubelet
      - containerd
    notify:
      - docker status
      - kubelet status
      - containerd status
    
  - name: Run the join command
    shell: $(cat /etc/.vagrantdata/kubeadm-join)
  
